In [16]:
# get the original data
import pandas as pd
import yfinance as yf
table = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
df = table[0]
# get a list of tickers
stockdata = df['Symbol'].to_list()
# get the data of the stocks of tickers that we want from 2022-01-21 to 2022-02-12
full_stock_data = yf.download(stockdata, '2022-01-21', '2022-02-12')
full_stock_data

[*********************100%***********************]  505 of 505 completed

2 Failed downloads:
- BRK.B: No data found, symbol may be delisted
- BF.B: No data found for this date range, symbol may be delisted

             Adj Close                                                 \
                     A        AAL         AAP        AAPL        ABBV
Date
2022-01-21  137.509995  16.299999  226.149994  162.203354  131.979996
2022-01-24  138.119995  16.410000  232.809998  161.414337  132.160004
2022-01-25  134.570007  16.459999  230.179993  159.576691  133.089996
2022-01-26  133.509995  16.240000  225.119995  159.486801  134.229996
2022-01-27  132.089996  15.780000  225.110001  159.017410  135.970001
2022-01-28  137.059998  15.640000  228.220001  170.113266  137.919998
2022-01-31  139.320007  16.469999  231.509995  174.557602  136.889999
2022-02-01  141.029999  16.830000  234.800003  174.387817  137.000000
2022-02-02  144.240005  16.959999  236.679993  175.616257  138.619995
2022-02-03  141.789993  16.570000  232.490005  172.679993  140.729996
2022-02-04  141.119995  16.450001  226.990005  172.389999  140.649994
2022-02-07  140.369995  17.280001  225.940002  171.660004  142.529999
2022-02-08  140.809998  18.260000  230.199997  174.830002  143.509995
2022-02-09  144.440002  18.760000  232.179993  176.279999  143.199997
2022-02-10  141.660004  18.709999  222.729996  172.119995  142.710007
2022-02-11  137.199997  17.610001  222.940002  168.639999  142.009995

                                                                        ...  \
                   ABC        ABMD         ABT         ACN        ADBE  ...
Date                                                                    ...
2022-01-21  131.092575  304.570007  125.830002  335.630005  499.910004  ...
2022-01-24  131.122467  311.940002  123.820000  339.000000  519.659973  ...
2022-01-25  130.634064  296.839996  123.269997  334.950012  502.720001  ...
2022-01-26  130.125717  297.140015  120.070000  329.890015  500.809998  ...
2022-01-27  134.252274  277.299988  120.440002  333.359985  493.049988  ...
2022-01-28  136.355408  277.250000  125.349998  342.850006  518.159973  ...
2022-01-31  135.757355  295.869995  127.459999  353.579987  534.299988  ...
2022-02-01  137.212616  301.350006  127.199997  353.420013  535.979980  ...
2022-02-02  135.637756  307.959991  130.039993  359.470001  533.090027  ...
2022-02-03  137.431900  290.519989  130.110001  345.549988  510.829987  ...
2022-02-04  136.166031  295.649994  129.710007  347.500000  513.539978  ...
2022-02-07  138.956924  289.839996  128.050003  343.959991  507.100006  ...
2022-02-08  141.777740  309.029999  128.649994  345.070007  511.309998  ...
2022-02-09  142.455521  315.920013  130.490005  355.529999  521.750000  ...
2022-02-10  141.080002  307.109985  127.760002  342.390015  495.019989  ...
2022-02-11  140.240005  294.820007  125.489998  329.179993  473.970001  ...

             Volume                                                          \
                XEL      XLNX       XOM     XRAY      XYL      YUM      ZBH
Date
2022-01-21  4885400   6162800  35995200  1271100  4093100  2130000  2972200
2022-01-24  4502300   6264700  41507000  1739500  1501200  2927300  2051500
2022-01-25  4756500   3114800  39278400  1785600  1636300  2667400  2347000
2022-01-26  4062100   3741800  35252400  1560900  1233300  1958600  2829700
2022-01-27  4442200  17926700  29174700  1074100  1096900  2680500  1877600
2022-01-28  3430400   5800900  30595700   898800  1122300  3465700  2250400
2022-01-31  3475800   4238500  36085500  1262300  1507600  2414100  1443900
2022-02-01  3372400   6007200  61033100  1539000  1380000  1485800  1035800
2022-02-02  2559800   9680100  30299300  1269500  1326600  1640300  2461100
2022-02-03  2530600   4842100  28529400   941700  3649700  1172600  1871200
2022-02-04  2517300   3193600  32176400   892600  2564500  1381100  1754900
2022-02-07  2652900   3259900  34949200   892000  1330000  1666600  6293600
2022-02-08  4155200   4838300  34356300  1247800  1750800  2345200  4522000
2022-02-09  3921800   6882000  40106100  1505100  1920400  3703000  2145500
2022-02-10  3232500   9316000  28527700  2286700  1505500  2178600  2445700
2022-02-11  3546800  25517400  41969100  1805400  1364400  2929300  1845200


               ZBRA     ZION      ZTS
Date
2022-01-21   488900  1996000  2633000
2022-01-24   853600  2327900  4093400
2022-01-25   537900  3832600  2673200
2022-01-26   592500  2315800  4532700
2022-01-27   624500  1781200  4606200
2022-01-28   569200  2186800  2963800
2022-01-31   364800  1503400  2591500
2022-02-01   330000  1158000  2143200
2022-02-02   482800   948100  2494300
2022-02-03   487800  1243100  1734500
2022-02-04   394600  1207400  1919800
2022-02-07   299800   809400  3303900
2022-02-08   615200  1998800  2880500
2022-02-09   678600  1351700  2026900
2022-02-10   772700  2554400  2809000
2022-02-11  1276000  1226200  3714600

[16 rows x 3030 columns]

In [17]:
# A. DATA. Choose a universe with at least 10 names. Remember our START DATE 
# from Exercise 1. Take the price of every stock in the universe on the START DATE as well as ONE WEEK prior and every multiple of ONE WEEK thereafter. 

# get the data we want --- the adjusted close price for each stock
stock_adjclose = full_stock_data['Adj Close']
# get the stock price at end of every week(as every weekend the stock market closed, we actually get the stock price of every Friday)
price_at_the_end_of_the_week = stock_adjclose.resample('W').ffill()
price_at_the_end_of_the_week

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2022-01-23,137.509995,16.299999,226.149994,162.203354,131.979996,131.092575,304.570007,125.830002,335.630005,499.910004,...,68.220001,187.789993,71.378700,52.930000,107.089996,124.239998,122.540001,494.179993,61.750000,200.330002
2022-01-30,137.059998,15.640000,228.220001,170.113266,137.919998,136.355408,277.250000,125.349998,342.850006,518.159973,...,69.839996,177.949997,74.454597,53.439999,101.709999,122.239998,120.889999,492.570007,68.150002,195.300003
2022-02-06,141.119995,16.450001,226.990005,172.389999,140.649994,136.166031,295.649994,129.710007,347.500000,513.539978,...,68.779999,209.020004,80.517395,52.299999,90.510002,125.269997,122.830002,503.089996,71.169998,199.539993
2022-02-13,137.199997,17.610001,222.940002,168.639999,142.009995,140.240005,294.820007,125.489998,329.179993,473.970001,...,66.959999,194.919998,80.209999,53.970001,89.239998,122.070000,116.209999,441.739990,73.220001,198.869995

In [18]:
# B. SIGNAL GENERATION. Compute all the one week returns for each name. These are the signals for our momentum strategy. 
# Provide a table of the signals (ticker, week)

# calculate the weekly return of the stock adjusted close
weekly_return = stock_adjclose.resample('W').ffill().pct_change() 
# as the first row would be NA, we delete the first row
weekly_return = weekly_return[1:]         
# generate a Series that we want to use as index
date = pd.Series(['week1','week2','week3'])    
# change the index for the dataframe to what we want
weekly_return = weekly_return.set_index(date)                       
weekly_return

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
week1,-0.003272,-0.040491,0.009153,0.048765,0.045007,0.040146,-0.089700,-0.003815,0.021512,0.036507,...,0.023747,-0.052399,0.043093,0.009635,-0.050238,-0.016098,-0.013465,-0.003258,0.103644,-0.025109
week2,0.029622,0.051790,-0.005390,0.013384,0.019794,-0.001389,0.066366,0.034783,0.013563,-0.008916,...,-0.015178,0.174600,0.081429,-0.021332,-0.110117,0.024787,0.016048,0.021357,0.044314,0.021710
week3,-0.027778,0.070517,-0.017842,-0.021753,0.009669,0.029919,-0.002807,-0.032534,-0.052719,-0.077053,...,-0.026461,-0.067458,-0.003818,0.031931,-0.014032,-0.025545,-0.053896,-0.121946,0.028804,-0.003358

In [19]:
# C. PORTFOLIO CONSTRUCTION. Assume we go long the top quintile and short the bottom quintile.
# Given a Target Notional of $2 Million of gross exposure (long and short), use signal weighting to compute the positions each week. 
# Bonus: Note that this simple portfolio construction is not perfectly hedged. What might you suggest to improve that? 

# in order to hedge the portfolio, maybe we can be more diversify, as stocks in one industry may all do well or bad,
# so maybe we can apply signal weighting separately in different industry and combine 
# the stocks that do top and last in its industry to contruct out portfolio

# signal weighting using week 1 data

# transpose the dataframe
df = weekly_return.T    
# sort the data by the order of week1 reuturn
week_1 = df.sort_values(by = 'week1', ascending = False)      
# get the top100 stocks to long
week_1_long = week_1.head(100) 
# get the sum of the return of the stocks that we long to be the denominator of the signal weighting
week_1_long = week_1_long.assign(sum1 = week_1_long.week1.sum())    
# use every stock's return to divided by the sum of all the returns to get their position 
week_1_long['signal_weighting_long'] = week_1_long.week1/week_1_long.sum1                   
# use their return to multiple their position to see if invest $1, how much money will each stock get as the return
week_1_long = week_1_long.assign(week2return = week_1_long.signal_weighting_long * week_1_long.week2)

# get the last 100 stocks to short
week_1_short = week_1.tail(100)   
# get the sum of the return of the stocks that we long to be the denominator of the signal weighting
week_1_short = week_1_short.assign(sum2 = week_1_short.week1.sum()) 
# use every stock's return to divided by the sum of all the returns and take the negative to get their position,as we short the data 
# so we should use negative position
week_1_short['signal_weighting_short'] = -week_1_short.week1/week_1_short.sum2 
# # use their return to multiple their position to see if invest $1, how much money will each stock get as the return
week_1_short =week_1_short.assign(week2return = week_1_short.signal_weighting_short * week_1_short.week2)



# signal weighting using week 2 data, the same process as how we do it for week 1
week_2 = df.sort_values(by = 'week2', ascending = False)
week_2_long = week_2.head(100)
week_2_long = week_2_long.assign(sum1 = week_2_long.week2.sum())
week_2_long['signal_weighting_long'] = week_2_long.week1/week_2_long.sum1
week_2_long = week_1_long.assign(week3return = week_2_long.signal_weighting_long * week_2_long.week3)

week_2_short = week_2.tail(100)
week_2_short = week_2_short.assign(sum2 = week_2_short.week2.sum())
week_2_short['signal_weighting_short'] = -week_2_short.week2/week_2_short.sum2
week_2_short =week_2_short.assign(week3return = week_2_short.signal_weighting_short * week_2_short.week3)

In [20]:
# D. TRADE EXECUTION. What transaction costs should we assume? 
# fee cost: 0.2bps, usually 0.1~0.2bps over 1-2M
# latency cost: as this is a relatively short-term trade, there definitely will have latency cost, just assume it to be 0.1bp
# fill cost: as we have 200 stocks here, the average fill cost is 0.5bps(include opportunity cost).0.15-1.5bps, as we use as an average, so we use 0.5bps

In [21]:
# E. BACKTEST. Finally, calculate the weekly returns of this strategy. Sum these to get the total return of the strategy. 

transaction_cost_pct = (0.2+0.1+0.5) * (0.0001)
# after using week 1's data to calculate the signal weightig, and using that sizing strategy, we have return of week 2:
week2Return = 1000000*(week_1_long['week2return'].sum() + week_1_short['week2return'].sum())
# after week 2, we have :
after_week2 = 2000000 + week2Return
# the money we have to enter week 3:
enter_week3 = after_week2 * (1 - transaction_cost_pct)
# after week 3, we have:
week3Return = (enter_week3/2)*(week_2_long['week3return'].sum() + week_2_short['week3return'].sum())
after_week3 = week3Return + enter_week3
# the money we have intotal to enter week 4:
enter_week4 = after_week3 * (1- transaction_cost_pct)
enter_week4

2008435.097809174